#
# Bases de Dados 2021/2022
# Trabalho Pr√°tico
#
# Authors:
#   Nuno Antunes <nmsa@dei.uc.pt>
#   BD 2022 Team - https://dei.uc.pt/lei/
#   University of Coimbra
version: '3'

services:
  db:
    build: ./postgresql
    container_name: db
    expose:
      - "5432"
    ports:
      - "5432:5432"
  web:
    build: ./python
    container_name: api
    volumes:
      - "./python/app:/app"
    expose:
      - "5000"
    ports:
      - "8080:5000"
    depends_on:
      - db
  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: grupox@grupox.pt
      PGADMIN_DEFAULT_PASSWORD: grupox
    ports:
      - "5050:80"     
